---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-app
spec:
  chart:
    spec:
      chart: promtail
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      version: '2.6.1'
  interval: 1m0s
  targetNamespace: observability

