---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tempo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      version: '>=0.15.0 <0.16.0'
  interval: 1m0s
  targetNamespace: observability

