---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-app
spec:
  interval: 5m0s
  path: ./infrastructure/gorilla/cne13
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloud-native-explab

